### ISSUE TITLE
Integration in kustomization.yml

### ISSUE THREAD

**Issue by cguertin14** [bbl/secretize#2]
Hi! Love the project, it's a great idea and fulfills many use-cases.
I've read the code and the documentation, but can't figure out how to integrate the binary provided in the release with the `kustomization.yml` file.

Is there a specific option to specify in the `kustomization.yml` file? Something like this maybe (assume `test-secretize.yml` contains a valid Secretize configuration):
```yaml
generators:
- test-secretize.yml
```

I've tried generators, transformers and other Kustomize options but can't seem to be able to use the plugin.
How can it actually be used with Kustomize?

Thanks! :)

PS: yes, [this](https://www.reddit.com/r/kubernetes/comments/jv3uh0/secretize_a_swiss_army_kustomize_plugin_for/gea9iko?utm_source=share&utm_medium=web2x&context=3) was also me.

**Comment by bbl** [comment]
Hello @cguertin14,
First of all, thank you for the feedback, I appreciate your interest!

This plugin can be used as a regular [kustomize exec plugin](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/execpluginguidedexample/#make-a-home-for-plugins). I'm working on the documentation & tutorials website, it will be available soon.
However, I'll describe a simple usage guide here as well.

Just for simplicity, I'll describe how to generate secrets from AWS Secrets Manager.

## Installation

1. Install [kustomize]([https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/](https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/)), if it's not already installed.
2. Install secretize binary into the kustomize plugins folder. By default, this folder will be `~/.config/kustomize/plugin`. You need to create a secretize subfolder and put the binary there:

```bash
mkdir -p ~/.config/kustomize/plugin/secretize/v1/secretgenerator
curl -L https://github.com/bbl/secretize/releases/download/v0.0.1/secretize-v0.0.1-linux-amd64.tar.gz | tar -xz -C  ~/.config/kustomize/plugin/secretize/v1/secretgenerator
```

## Usage

1. Create a secret with AWS Console or by using  `aws` cli, e.g.:

```bash
aws secretsmanager create-secret --name mySecret  --secret-string 'superSecretString'
```

2. Create a `kustomization.yaml` file with the following content:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - secret-generator.yaml
```

3. Create the `secret-generator.yaml` file:

```yaml
apiVersion: secretize/v1
kind: SecretGenerator
metadata:
  name: my-secret
sources:
- provider: aws-sm
  literals:
    - mySecret
```

4. Export AWS variables, e.g.:

```bash
export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
export AWS_DEFAULT_REGION=us-west-2
```

5. Run kustomize:

```bash
kustomize build --enable_alpha_plugins
```

**Comment by bbl** [comment]
Closing the issue now. 
Please feel free to re-open if you have any questions.
