### ISSUE TITLE
feat: Azure KeyVault - NewAuthorizerFromCLIWithResource

### ISSUE THREAD

**Issue by lukasmrtvy** [bbl/secretize#6]
Hello. Would be nice to implement also `NewAuthorizerFromCLIWithResource` from sdk ( CLI authentication )  like in https://github.com/variantdev/vals/blob/master/pkg/providers/azurekeyvault/azurekeyvault.go
This will allow us to use `az login && kustomize build . `

**Comment by bbl** [comment]
Hello! Thanks for the idea, I will add this feature!

**Comment by lukasmrtvy** [comment]
@bbl Thanks. MSI is also important. ( This would be suitable for ArgoCD )

**Comment by bbl** [comment]
Added both into the [v0.0.2 release](https://github.com/bbl/secretize/releases/tag/0.0.2).
You'll need to update the binary in your kustomize plugin folder.

Closing this for now, please feel free to reopen if you have any questions!
