### ISSUE TITLE
FYI: Your plugin has been added to Awesome Kustomize list

### ISSUE THREAD

**Issue by aabouzaid** [bbl/secretize#9]
Hi :wave: 

I just started an [Awesome Kustomize](https://github.com/aabouzaid/awesome-kustomize/#generators) :tada:
Because after using Kustomize for 3 years, there was no central place for Kustomize resources.

I've found your repo via GitHub labels, and I find it totally helpful.

Thank you :rocket:

**Comment by bbl** [comment]
Hello @aabouzaid!
Great stuff, thank you!
